name: Deploy to GCP

on:
  push:
    branches:
      - main  # Ejecuta en la rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Google Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Authenticate Docker
        run: gcloud auth configure-docker gcr.io

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/festive-bazaar-452803-c1/ml-api:latest .
          docker push gcr.io/festive-bazaar-452803-c1/ml-api:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0  # Puedes ajustar la versión según necesites

      - name: Terraform Init
        run: terraform init
        working-directory: challenge/infra/terraform  # Ajusta según tu estructura de archivos

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: challenge/infra/terraform
